import * as fs from 'fs';
import * as path from 'path';
import { generate } from 'multiple-cucumber-html-reporter';

/**
 * Generate Cucumber HTML report from JSON results
 * Migrated from WebDriverIO report generation
 */
export async function generateReport(): Promise<void> {
  try {
    console.log('📊 Generating Cucumber HTML report...');
    
    // Ensure reports directory exists
    const reportsDir = './reports';
    if (!fs.existsSync(reportsDir)) {
      fs.mkdirSync(reportsDir, { recursive: true });
    }
    
    // Check if cucumber report JSON exists
    const cucumberJsonPath = path.join(reportsDir, 'cucumber-report.json');
    if (!fs.existsSync(cucumberJsonPath)) {
      console.log('⚠️  No Cucumber JSON report found, skipping HTML report generation');
      return;
    }
    
    // Generate HTML report
    generate({
      jsonDir: reportsDir,
      reportPath: reportsDir,
      reportName: 'Playwright BDD Test Report',
      pageTitle: 'Playwright BDD Test Results',
      displayDuration: true,
      displayReportTime: true,
      useCDN: false,
      pageFooter: '<div><p>Generated by Playwright BDD Framework</p></div>',
      customData: {
        title: 'Test Execution Info',
        data: [
          { label: 'Project', value: 'Playwright BDD Migration' },
          { label: 'Framework', value: 'Playwright + Cucumber' },
          { label: 'Environment', value: process.env.NODE_ENV || 'development' },
          { label: 'Browser', value: process.env.BROWSER || 'chromium' },
          { label: 'Execution Date', value: new Date().toISOString() }
        ]
      },
      metadata: {
        browser: {
          name: process.env.BROWSER || 'chromium',
          version: 'latest'
        },
        device: process.platform,
        platform: {
          name: process.platform,
          version: process.version
        }
      }
    });
    
    console.log('✅ Cucumber HTML report generated successfully');
    console.log(`📁 Report location: ${path.resolve(reportsDir, 'index.html')}`);
    
  } catch (error) {
    console.error('❌ Failed to generate Cucumber report:', error);
    throw error;
  }
}

/**
 * Generate report if called directly
 */
if (require.main === module) {
  generateReport().catch(console.error);
}